# Generated by Django 4.1.7 on 2023-05-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(blank=True, null=True)),
                ('expediente', models.TextField(blank=True, null=True)),
                ('unidad_fiscalizable', models.TextField(blank=True, null=True)),
                ('nombre_razon_social', models.TextField(blank=True, null=True)),
                ('categoria', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
