# Generated by Django 4.1.7 on 2023-05-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_script', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
